apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  type: LoadBalancer
  ports:
  - name: input
    port: 4560
    targetPort: 4560
    protocol: TCP
  - name: beats
    port: 4561
    targetPort: 4561
    protocol: TCP
